name: valync_example
description: Example Flutter app demonstrating the valync package.
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  valync:
    path: ../..
  http: ^1.6.0
  option_result: ^3.3.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
