name: valync
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  analyzer: ^10.0.1
  build: ^4.0.4
  flutter:
    sdk: flutter
  http: ^1.4.0
  logger: ^2.6.0
  option_result: ^3.2.1
  source_gen: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
