name: valync
description: "Flutter HTTP client with typed Result pattern"
version: 0.1.3
homepage: https://github.com/epikoder/valync-flutter

environment:
  sdk: ^3.5.3
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  logger: ^2.6.0
  option_result: ^3.3.0
  source_gen: ^4.2.0
  build: ^4.0.4
  analyzer: ">=9.0.0 <12.0.0"

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
