import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:http/testing.dart';
import 'package:option_result/result.dart';
import 'package:valync/valync.dart';

// ---------------------------------------------------------------------------
// Models
// ---------------------------------------------------------------------------

class User implements JsonType<User> {
  final String id;
  final String name;
  final String email;

  User({required this.id, required this.name, required this.email});

  @override
  User fromJson(dynamic json) => User(
        id: json['id'] as String,
        name: json['name'] as String,
        email: json['email'] as String,
      );
}

class Post implements JsonType<Post> {
  final String id;
  final String title;

  Post({required this.id, required this.title});

  @override
  Post fromJson(dynamic json) => Post(
        id: json['id'] as String,
        title: json['title'] as String,
      );
}

// ---------------------------------------------------------------------------
// Mock HTTP client
// ---------------------------------------------------------------------------

final _mockClient = MockClient((request) async {
  await Future<void>.delayed(
      const Duration(milliseconds: 300)); // simulate latency

  final path = request.url.path;

  if (path == '/users/1') {
    return http.Response(
      jsonEncode({
        'status': 'success',
        'data': {'id': '1', 'name': 'Alice', 'email': 'alice@example.com'},
      }),
      200,
    );
  }

  if (path == '/posts') {
    return http.Response(
      jsonEncode({
        'status': 'success',
        'data': [
          {'id': '1', 'title': 'Hello World'},
          {'id': '2', 'title': 'Getting started with valync'},
        ],
      }),
      200,
    );
  }

  if (path == '/logout') {
    return http.Response('', 204);
  }

  if (path == '/error') {
    return http.Response(
      jsonEncode({
        'status': 'failed',
        'error': {
          'name': 'NotFound',
          'message': 'Resource not found',
          'code': '404'
        },
      }),
      200,
    );
  }

  return http.Response('Not found', 404);
});

// ---------------------------------------------------------------------------
// App
// ---------------------------------------------------------------------------

void main() {
  // Register models — normally generated by build_runner into type_factories.dart.
  // Built-in types (EmptyResponse, ListResponse, JsonObjectResponse) are
  // pre-registered by valync automatically.
  registerFactory(User, User(id: '', name: '', email: ''));
  registerFactory(Post, Post(id: '', title: ''));

  runApp(const ValyncExampleApp());
}

class ValyncExampleApp extends StatelessWidget {
  const ValyncExampleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'valync example',
      theme: ThemeData(colorSchemeSeed: Colors.indigo, useMaterial3: true),
      home: const ExampleScreen(),
    );
  }
}

class ExampleScreen extends StatefulWidget {
  const ExampleScreen({super.key});

  @override
  State<ExampleScreen> createState() => _ExampleScreenState();
}

class _ExampleScreenState extends State<ExampleScreen> {
  final _log = <String>[];
  bool _loading = false;

  // Runs [fn] inside the mock HTTP client zone.
  Future<T> _mocked<T>(Future<T> Function() fn) =>
      http.runWithClient(fn, () => _mockClient);

  void _append(String line) => setState(() => _log.add(line));

  Future<void> _fetchUser() async {
    setState(() => _loading = true);
    final result = await _mocked(
      () => valync<User>('https://api.example.com/users/1'),
    );
    switch (result) {
      case Ok(:final value):
        _append('GET /users/1 → ${value.name} <${value.email}>');
      case Err(:final error):
        _append('GET /users/1 → ERROR: $error');
    }
    setState(() => _loading = false);
  }

  Future<void> _fetchPosts() async {
    setState(() => _loading = true);

    // createClient with a shared header and an onError retry hook.
    final client = createClient(
      headers: {'X-App-Version': '1.0.0'},
      config: ValyncClientConfig(
        onError: (error) async {
          _append('onError triggered: ${error.name}');
          return false; // don't retry in this example
        },
      ),
    );

    final result = await _mocked(
      () => client<ListResponse>('https://api.example.com/posts'),
    );

    switch (result) {
      case Ok(:final value):
        final posts = value.apply((e) => Post(id: '', title: '').fromJson(e));
        for (final p in posts) {
          _append('  • [${p.id}] ${p.title}');
        }
        _append('GET /posts → ${posts.length} posts');
      case Err(:final error):
        _append('GET /posts → ERROR: $error');
    }

    setState(() => _loading = false);
  }

  Future<void> _logout() async {
    setState(() => _loading = true);
    final result = await _mocked(
      () => valync<EmptyResponse>(
        'https://api.example.com/logout',
        method: HttpMethod.post,
      ),
    );
    switch (result) {
      case Ok():
        _append('POST /logout → 204 No Content');
      case Err(:final error):
        _append('POST /logout → ERROR: $error');
    }
    setState(() => _loading = false);
  }

  Future<void> _triggerError() async {
    setState(() => _loading = true);
    final result = await _mocked(
      () => valync<User>('https://api.example.com/error'),
    );
    switch (result) {
      case Ok(:final value):
        _append('GET /error → ${value.name}');
      case Err(:final error):
        _append(
            'GET /error → ${error.name}: ${error.message} (code: ${error.code.unwrapOr('—')})');
    }
    setState(() => _loading = false);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('valync example')),
      body: Column(
        children: [
          Padding(
            padding: const EdgeInsets.all(12),
            child: Wrap(
              spacing: 8,
              runSpacing: 8,
              children: [
                FilledButton(
                    onPressed: _loading ? null : _fetchUser,
                    child: const Text('GET user')),
                FilledButton(
                    onPressed: _loading ? null : _fetchPosts,
                    child: const Text('GET posts (list)')),
                FilledButton(
                    onPressed: _loading ? null : _logout,
                    child: const Text('POST logout (204)')),
                FilledButton.tonal(
                    onPressed: _loading ? null : _triggerError,
                    child: const Text('Trigger error')),
                OutlinedButton(
                  onPressed: () => setState(() => _log.clear()),
                  child: const Text('Clear'),
                ),
              ],
            ),
          ),
          if (_loading) const LinearProgressIndicator(),
          Expanded(
            child: ListView.builder(
              padding: const EdgeInsets.symmetric(horizontal: 12),
              itemCount: _log.length,
              itemBuilder: (_, i) => Text(
                _log[i],
                style: const TextStyle(fontFamily: 'monospace', fontSize: 13),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
